/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as MediaRouteImport } from './routes/media'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as BetekintesRouteImport } from './routes/betekintes'
import { Route as IndexRouteImport } from './routes/index'

const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const BetekintesRoute = BetekintesRouteImport.update({
  id: '/betekintes',
  path: '/betekintes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/betekintes': typeof BetekintesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/media': typeof MediaRoute
  '/rolam': typeof RolamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/betekintes': typeof BetekintesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/media': typeof MediaRoute
  '/rolam': typeof RolamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/betekintes': typeof BetekintesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/media': typeof MediaRoute
  '/rolam': typeof RolamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/betekintes' | '/kapcsolat' | '/media' | '/rolam'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/betekintes' | '/kapcsolat' | '/media' | '/rolam'
  id: '__root__' | '/' | '/betekintes' | '/kapcsolat' | '/media' | '/rolam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetekintesRoute: typeof BetekintesRoute
  KapcsolatRoute: typeof KapcsolatRoute
  MediaRoute: typeof MediaRoute
  RolamRoute: typeof RolamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betekintes': {
      id: '/betekintes'
      path: '/betekintes'
      fullPath: '/betekintes'
      preLoaderRoute: typeof BetekintesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetekintesRoute: BetekintesRoute,
  KapcsolatRoute: KapcsolatRoute,
  MediaRoute: MediaRoute,
  RolamRoute: RolamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
